FROM python:3.8-slim

# Setting the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir flask

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV SERVER_ID=1

# Run app.py when the container launches
CMD ["python", "app.py"]
